// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LuxSalon.Services.Database;

#nullable disable

namespace LuxSalon.Services.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260726032304_DodajResetLozinke")]
    partial class DodajResetLozinke
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuxSalon.Services.Database.Frizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografija")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Specijalizacija")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Frizeri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografija = "10 godina iskustva u šišanju i farbanju.",
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Specijalizacija = "Kosa - šišanje i farbanje",
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            Biografija = "Specijalista za njegu lica, ruku i nogu.",
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Specijalizacija = "Njega lica, manikura, pedikura",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.FrizerOcjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrizerId")
                        .HasColumnType("int");

                    b.Property<int>("KlijentId")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrizerId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("TerminId")
                        .IsUnique();

                    b.ToTable("FrizerOcjene");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.FrizerUsluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FrizerId")
                        .HasColumnType("int");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrizerId");

                    b.HasIndex("UslugaId");

                    b.ToTable("FrizerUsluge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FrizerId = 1,
                            UslugaId = 1
                        },
                        new
                        {
                            Id = 2,
                            FrizerId = 1,
                            UslugaId = 2
                        },
                        new
                        {
                            Id = 3,
                            FrizerId = 1,
                            UslugaId = 3
                        },
                        new
                        {
                            Id = 4,
                            FrizerId = 1,
                            UslugaId = 4
                        },
                        new
                        {
                            Id = 5,
                            FrizerId = 2,
                            UslugaId = 5
                        },
                        new
                        {
                            Id = 6,
                            FrizerId = 2,
                            UslugaId = 6
                        },
                        new
                        {
                            Id = 7,
                            FrizerId = 2,
                            UslugaId = 7
                        },
                        new
                        {
                            Id = 8,
                            FrizerId = 2,
                            UslugaId = 8
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.IstorijaStatusaTermina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoviStatus")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PrethodniStatus")
                        .HasColumnType("int");

                    b.Property<int>("PromijenioKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromijenioKorisnikId");

                    b.HasIndex("TerminId");

                    b.ToTable("IstorijaStatusaTermina");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Notifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<int?>("TerminId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("TerminId");

                    b.ToTable("Notifikacije");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SlikaBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Obavijesti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naslov = "Dobrodošli u LuxSalon!",
                            Tekst = "Sada možete zakazivati termine direktno kroz aplikaciju, pratiti svoje rezervacije i primati obavještenja uživo."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naslov = "Novi tretmani njege lica",
                            Tekst = "Uveli smo nove anti-age tretmane lica. Rezervišite termin i isprobajte ih uz popust za prve klijente."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naslov = "Radno vrijeme za praznike",
                            Tekst = "Za vrijeme predstojećih praznika salon radi po skraćenom radnom vremenu. Provjerite dostupne termine u aplikaciji."
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.PasswordResetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPlacanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPovrata")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaypalOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaypalTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminId")
                        .IsUnique();

                    b.ToTable("Placanja");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.RadnoVrijeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanUSedmici")
                        .HasColumnType("int");

                    b.Property<int>("FrizerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("KrajRada")
                        .HasColumnType("time");

                    b.Property<bool>("NeRadi")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("PocetakRada")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("FrizerId", "DanUSedmici")
                        .IsUnique();

                    b.ToTable("RadnaVremena");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanUSedmici = 1,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DanUSedmici = 2,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DanUSedmici = 3,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DanUSedmici = 4,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DanUSedmici = 5,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DanUSedmici = 6,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 15, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DanUSedmici = 0,
                            FrizerId = 1,
                            KrajRada = new TimeSpan(0, 0, 0, 0, 0),
                            NeRadi = true,
                            PocetakRada = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DanUSedmici = 1,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DanUSedmici = 2,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DanUSedmici = 3,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DanUSedmici = 4,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DanUSedmici = 5,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 17, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DanUSedmici = 6,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 15, 0, 0, 0),
                            NeRadi = false,
                            PocetakRada = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DanUSedmici = 0,
                            FrizerId = 2,
                            KrajRada = new TimeSpan(0, 0, 0, 0, 0),
                            NeRadi = true,
                            PocetakRada = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default customer role",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zaposlenik koji izvodi usluge",
                            IsActive = true,
                            Name = "Frizer"
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrizerId")
                        .HasColumnType("int");

                    b.Property<int>("KlijentId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeMinuta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrizerId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("UslugaId");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@gmail.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "5kRBQg4Ufcx4hAknG7P9zhfLPvY=",
                            PasswordSalt = "FmvmUwPsJyRRffhNRQvbrA==",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@gmail.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "GBoyh1WP+OMgGjqRj6vK6L1+oGc=",
                            PasswordSalt = "0AXpKx6xRp9xM42jCf/PiA==",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin3@gmail.com",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "x6JHKCTQywdAzTcZxGWFvrKPORM=",
                            PasswordSalt = "IwhTfKQNgyqWfOlTqCDXrg==",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@gmail.com",
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "E0fA2/f9GZvIRRt/cgqQemG/Cog=",
                            PasswordSalt = "TiJxWTJcd7sBSiWNbhK9Vw==",
                            Username = "customer1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@gmail.com",
                            FirstName = "Eve",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "Ov4LxpWKXXV9dwMYvBgqODdzIt0=",
                            PasswordSalt = "KtWF6g7SemBqs4nVWV4Ziw==",
                            Username = "customer2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frizer1@luxsalon.com",
                            FirstName = "Amina",
                            IsActive = true,
                            LastName = "Hairstyle",
                            PasswordHash = "IV/0YG2BWZ+smbLeXBpH+ZbyMLU=",
                            PasswordSalt = "nxuCJ53rAjnOZO8Dh/rRoQ==",
                            Username = "frizer1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frizer2@luxsalon.com",
                            FirstName = "Damir",
                            IsActive = true,
                            LastName = "Stilist",
                            PasswordHash = "eJPc308v8Kl8xYjCa5IYnV5g2Dw=",
                            PasswordSalt = "s+SJ0wp/uSRl29HAF6L2yw==",
                            Username = "frizer2"
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Usluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tagovi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrajanjeMinuta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UslugaKategorijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UslugaKategorijaId");

                    b.ToTable("Usluge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Muško šišanje",
                            Opis = "Klasično muško šišanje",
                            Tagovi = "kosa,musko,sisanje",
                            TrajanjeMinuta = 30,
                            UslugaKategorijaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 25m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Žensko šišanje",
                            Opis = "Šišanje i oblikovanje za žene",
                            Tagovi = "kosa,zensko,sisanje",
                            TrajanjeMinuta = 45,
                            UslugaKategorijaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 60m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Farbanje kose",
                            Opis = "Jednobojno farbanje kose",
                            Tagovi = "kosa,farbanje,boja",
                            TrajanjeMinuta = 90,
                            UslugaKategorijaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 80m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pramenovi",
                            Opis = "Melirani pramenovi",
                            Tagovi = "kosa,farbanje,pramenovi",
                            TrajanjeMinuta = 120,
                            UslugaKategorijaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 40m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Čišćenje lica",
                            Opis = "Dubinsko čišćenje lica",
                            Tagovi = "lice,njega,cisenje",
                            TrajanjeMinuta = 60,
                            UslugaKategorijaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cijena = 55m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Anti-age tretman lica",
                            Opis = "Tretman protiv starenja kože",
                            Tagovi = "lice,njega,antiage",
                            TrajanjeMinuta = 60,
                            UslugaKategorijaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cijena = 20m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Manikura",
                            Opis = "Klasična manikura",
                            Tagovi = "ruke,manikura,njega",
                            TrajanjeMinuta = 40,
                            UslugaKategorijaId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cijena = 25m,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pedikura",
                            Opis = "Klasična pedikura",
                            Tagovi = "noge,pedikura,njega",
                            TrajanjeMinuta = 50,
                            UslugaKategorijaId = 4
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.UslugaKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("UslugaKategorije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Šišanje",
                            Opis = "Šišanje i oblikovanje kose"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Farbanje",
                            Opis = "Bojenje i tretmani boje kose"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Njega lica",
                            Opis = "Tretmani njege i čišćenja lica"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Njega ruku i nogu",
                            Opis = "Manikura i pedikura"
                        });
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Frizer", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.FrizerOcjena", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Frizer", "Frizer")
                        .WithMany()
                        .HasForeignKey("FrizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.User", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frizer");

                    b.Navigation("Klijent");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.FrizerUsluga", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Frizer", "Frizer")
                        .WithMany("FrizerUsluge")
                        .HasForeignKey("FrizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.Usluga", "Usluga")
                        .WithMany("FrizerUsluge")
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frizer");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.IstorijaStatusaTermina", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.User", "PromijenioKorisnik")
                        .WithMany()
                        .HasForeignKey("PromijenioKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromijenioKorisnik");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Notifikacija", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.User", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Korisnik");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.PasswordResetCode", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Placanje", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Termin", "Termin")
                        .WithOne("Placanje")
                        .HasForeignKey("LuxSalon.Services.Database.Placanje", "TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.RadnoVrijeme", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Frizer", "Frizer")
                        .WithMany()
                        .HasForeignKey("FrizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frizer");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Termin", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Frizer", "Frizer")
                        .WithMany("Termini")
                        .HasForeignKey("FrizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.User", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.Usluga", "Usluga")
                        .WithMany("Termini")
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Frizer");

                    b.Navigation("Klijent");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.UserRole", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxSalon.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Usluga", b =>
                {
                    b.HasOne("LuxSalon.Services.Database.UslugaKategorija", "UslugaKategorija")
                        .WithMany("Usluge")
                        .HasForeignKey("UslugaKategorijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UslugaKategorija");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Frizer", b =>
                {
                    b.Navigation("FrizerUsluge");

                    b.Navigation("Termini");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Termin", b =>
                {
                    b.Navigation("Placanje");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.Usluga", b =>
                {
                    b.Navigation("FrizerUsluge");

                    b.Navigation("Termini");
                });

            modelBuilder.Entity("LuxSalon.Services.Database.UslugaKategorija", b =>
                {
                    b.Navigation("Usluge");
                });
#pragma warning restore 612, 618
        }
    }
}
